
package com.ws.calculadora;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICalculadora", targetNamespace = "http://calculadora.ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICalculadora {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suma", targetNamespace = "http://calculadora.ws.com/", className = "com.ws.calculadora.Suma")
    @ResponseWrapper(localName = "sumaResponse", targetNamespace = "http://calculadora.ws.com/", className = "com.ws.calculadora.SumaResponse")
    @Action(input = "http://calculadora.ws.com/ICalculadora/sumaRequest", output = "http://calculadora.ws.com/ICalculadora/sumaResponse")
    public double suma(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resta", targetNamespace = "http://calculadora.ws.com/", className = "com.ws.calculadora.Resta")
    @ResponseWrapper(localName = "restaResponse", targetNamespace = "http://calculadora.ws.com/", className = "com.ws.calculadora.RestaResponse")
    @Action(input = "http://calculadora.ws.com/ICalculadora/restaRequest", output = "http://calculadora.ws.com/ICalculadora/restaResponse")
    public double resta(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplicacion", targetNamespace = "http://calculadora.ws.com/", className = "com.ws.calculadora.Multiplicacion")
    @ResponseWrapper(localName = "multiplicacionResponse", targetNamespace = "http://calculadora.ws.com/", className = "com.ws.calculadora.MultiplicacionResponse")
    @Action(input = "http://calculadora.ws.com/ICalculadora/multiplicacionRequest", output = "http://calculadora.ws.com/ICalculadora/multiplicacionResponse")
    public double multiplicacion(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://calculadora.ws.com/", className = "com.ws.calculadora.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://calculadora.ws.com/", className = "com.ws.calculadora.DivisionResponse")
    @Action(input = "http://calculadora.ws.com/ICalculadora/divisionRequest", output = "http://calculadora.ws.com/ICalculadora/divisionResponse")
    public double division(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
